name: Lambda Deployment
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/lambda-deploy.yml'

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION: youtube-downloader-prod-api

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEPLOY_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install awscli

      - name: Package Lambda
        working-directory: ./scripts
        run: ./package_lambda.sh

      - name: Deploy Lambda
        working-directory: ./scripts
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION }} \
            --zip-file fileb://../lambda_package.zip \
            --region ${{ env.AWS_REGION }}