name: Terraform Destroy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (dev/staging)'
        required: true
        default: 'dev'

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.5.0

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.TF_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -input=false -auto-approve -var="environment=${{ github.event.inputs.environment }}"